spring:
  application:
    name: hapbang
  modulith:
    detection-strategy: explicitly-annotated
  docker:
    compose:
      file: docker/compose.yaml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
